SignUp/config/routes.rb
Rails.application.routes.draw do

	resources :boards, :posts, :welcomeposts, :wdiposts, :uxdiposts, :dmposts, :fewdposts, :pmposts, :dsposts, :bdsposts, :vdposts, :mdposts, :uxdposts, :anyposts, :jobposts


  root :to => 'sessions#new'
	get '/signup' => 'users#new'
	post "users" => "users#create"
  # Pages
	get "/contact" => "pages#contact"
	get "/about" => "pages#about"
	get "/help" => "pages#help"
  # Sessions
	get "/login" => "sessions#new"
	post "/login" => "sessions#create"
	get "/logout" => "sessions#destroy"
  # Boards
  get '/forums' => "boards#forums"
  get 'boards' => 'boards#index'
  get '/new_board' => 'boards#new_board'
  post '/forums' => 'boards#create'

# Threads
  patch "anyposts/:id" => "anyposts#update"
  delete "anyposts/:id" => "anyposts#destroy"
  patch "bdsposts/:id" => "bdsposts#update"
  delete "bdsposts/:id" => "bdsposts#destroy"
  patch "dmposts/:id" => "dmposts#update"
  delete "dmposts/:id" => "dmposts#destroy"
  patch "dsposts/:id" => "dsposts#update"
  delete "dsposts/:id" => "dsposts#destroy"
  patch "fewdposts/:id" => "fewdposts#update"
  delete "fewdposts/:id" => "fewdposts#destroy"
  patch "jobposts/:id" => "jobposts#update"
  delete "jobposts/:id" => "jobposts#destroy"
  patch "mdposts/:id" => "mdposts#update"
  delete "mdposts/:id" => "mdposts#destroy"
  patch "pmposts/:id" => "pmposts#update"
  delete "pmposts/:id" => "pmposts#destroy"
  patch "uxdiposts/:id" => "uxdiposts#update"
  delete "uxdiposts/:id" => "uxdiposts#destroy"
  patch "uxdposts/:id" => "uxdposts#update"
  delete "uxdposts/:id" => "uxdposts#destroy"
  patch "vdposts/:id" => "vdposts#update"
  delete "vdposts/:id" => "vdposts#destroy"
  patch "wdiposts/:id" => "wdiposts#update"
  delete "wdoposts/:id" => "wdiposts#destroy"
  patch "welcomeposts/:id" => "welcomeposts#update"
  delete "welcomeposts/:id" => "welcomeposts#destroy"

end

SignUp/app/models/anypost.rb
class Anypost < ActiveRecord::Base
end

SignUp/app/models/bdspost.rb
class Bdspost < ActiveRecord::Base
end

SignUp/app/models/board.rb
class Board < ActiveRecord::Base
	has_many :threads
  belongs_to :user

	def thread_count
	end

	def post_count
		# board.post.count
	end

	def last_post
	end


end

SignUp/app/models/dmpost.rb
class Dmpost < ActiveRecord::Base
end

SignUp/app/models/dspost.rb
class Dspost < ActiveRecord::Base
end

SignUp/app/models/fewdpost.rb
class Fewdpost < ActiveRecord::Base
end

SignUp/app/models/jobpost.rb
class Jobpost < ActiveRecord::Base
end

SignUp/app/models/mdpost.rb
class Mdpost < ActiveRecord::Base
end

SignUp/app/models/pmpost.rb
class Pmpost < ActiveRecord::Base
end

SignUp/app/models/post.rb
class Post < ActiveRecord::Base
end

SignUp/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
  has_many :boards





end

SignUp/app/models/uxdipost.rb
class Uxdipost < ActiveRecord::Base
end

SignUp/app/models/uxdpost.rb
class Uxdpost < ActiveRecord::Base
end

SignUp/app/models/vdpost.rb
class Vdpost < ActiveRecord::Base
end

SignUp/app/models/wdipost.rb
class Wdipost < ActiveRecord::Base
end

SignUp/app/models/welcomepost.rb
class Welcomepost < ActiveRecord::Base
end

SignUp/app/controllers/dmposts_controller.rb
class DmpostsController < ApplicationController
  def index
    @dmposts = Dmpost.all
  end

  def new
    @dmpost = Dmpost.new
  end

  def create
    @dmpost = Dmpost.new(dmpost_params)
      if @dmpost.save
        redirect_to dmposts_path
      else
        render 'new'
      end
  end

  def edit
    @dmpost = Dmpost.find(params[:id])
  end

  def update
    @dmpost = Dmpost.find(params[:id])

    if @dmpost.update_attributes(dmpost_params)
      redirect_to dmposts_path
    else
      render "edit"
    end
  end

  def destroy
    @dmpost = Dmpost.find(params[:id])
    @dmpost.destroy
    redirect_to dmposts_path
  end


      private

      def dmpost_params
        params.require(:dmpost).permit(:title, :body)
      end

end

SignUp/app/helpers/boards_helper.rb
module BoardsHelper
end

SignUp/app/helpers/dmposts_helper.rb
module DmpostsHelper
end

SignUp/app/helpers/dsposts_helper.rb
module DspostsHelper
end

SignUp/app/helpers/pages_helper.rb
module PagesHelper
end

SignUp/app/helpers/posts_helper.rb
module PostsHelper
end

SignUp/app/helpers/users_helper.rb
module UsersHelper
end

SignUp/app/views/dmposts/edit.html.erb
<!-- Navigation Bar -->
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" date-toggle="collapse"data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="https://generalassemb.ly"><span class="red">G</span>eneral <span class="red">A</span>ssembly</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active">
          <a href="/boards">Forums</a>
        </li>
        <li>
          <a href="/about">About</a>
        </li>
        <li>
          <a href="/contact">Contact</a>
        </li>
        <li><%= link_to "Logout", "/logout" %></li>
      </ul>
    </div>
  </div>
</nav>

<!-- Header and Location -->
<div class="container">
<h1 class="white">Edit This Thread</h1>
  <span class="white"><h3><%=link_to "Forums", boards_path %> > <%= link_to "Digital Marketing", dmposts_path %> > <%= link_to "Create", dmposts_path %></h3></span><br>

<!-- Edit Form -->
<%= form_for @dmpost do |f| %>
<%= link_to "Go Back", dmposts_path, class:"pull-right btn btn-primary " %><br><br>
  <span class="white">Title</span><br> <%= f.text_field :title, class:"form-control" %><br>
  <span class="white">Description</span><br> <%= f.text_field :body, class:"form-control" %><br>

  <%= f.submit "Edit Thread!" %>

<% end %>

<%= link_to "Go Back", dmposts_path %>

</div>

SignUp/app/views/dmposts/index.html.erb
<!-- Navigation Bar -->
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" date-toggle="collapse"data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="https://generalassemb.ly"><span class="red">G</span>eneral <span class="red">A</span>ssembly</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active">
          <a href="/boards">Forums</a>
        </li>
        <li>
          <a href="/about">About</a>
        </li>
        <li>
          <a href="/contact">Contact</a>
        </li>
        <li><%= link_to "Logout", "/logout" %></li>
      </ul>
    </div>
  </div>
</nav>


<!-- Header and Location -->
<div class="container">
  <span class="white"><h1>Digital Marketing</h1>
    <h3><%=link_to "Forums", boards_path %> > <%= link_to "Digital Marketing", dmposts_path %><span class="pull-right"><%= link_to "Create post", new_dmpost_path, class:"btn btn-primary" %></span></h3></span>

<!-- Threads -->
  <div class="panel panel-default">
    <% @dmposts.each do |dmpost| %>
      <div class="panel-heading"><%= dmpost.title %><span class="pull-right"><%= link_to "  ", edit_dmpost_path(dmpost), class:"glyphicon glyphicon-pencil" %><span class="spacing"></span><%= link_to "  ", dmpost, method: :delete, data: {confirm: "Are you sure you want to delete this thread?"}, class:"glyphicon glyphicon-trash" %></span></div>
      <div class="panel-body">
      <%= dmpost.body %>
    </div>
    <% end %>
  </div>
</div>

SignUp/app/views/dmposts/new.html.erb
<!-- Navigation Bar -->
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" date-toggle="collapse"data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="https://generalassemb.ly"><span class="red">G</span>eneral <span class="red">A</span>ssembly</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active">
          <a href="/boards">Forums</a>
        </li>
        <li>
          <a href="/about">About</a>
        </li>
        <li>
          <a href="/contact">Contact</a>
        </li>
        <li><%= link_to "Logout", "/logout" %></li>
      </ul>
    </div>
  </div>
</nav>

<!-- Header and Location -->
<div class="container">
  <span class="white"><h1>Create A New Thread</h1>
    <h3><%=link_to "Forums", boards_path %> > <%= link_to "Digital Marketing", dmposts_path %> > <%= link_to "Create", dmposts_path %></h3></span><br>

<!-- Create New Thread Form -->
  <%= form_for @dmpost do |f| %>
    <%= link_to "Go Back", dmposts_path, class:"pull-right btn btn-primary " %><br><br>
    <span class="white">Title</span><br>
      <%= f.text_field :title, class:"form-control" %><br>
    <span class="white">Message</span><br>
    <%= f.text_field :body, class:"form-control" %>
      <br></textarea>
      <%= f.submit 'submit', class:"button" %>
  <% end %>

</div>

SignUp/app/views/dmposts/show.html.erb
<!-- Thread Title -->
<h1><%= dmpost.title %></h1>

<!-- Description of Thread -->
<p><%= dmpost.body %></p>

<%= link_to "Edit this thread", edit_dmpost_path(@dmpost) %>

<%= link_to "Delete this thread!",:dmpost, method: :delete, data: {confirm: "Are you sure you want to delete this thread?"} %>

<!-- Provide a link back to our index page -->
<%= link_to "Go Back", dmposts_path %>